<h1 style='color:#1B127A;'>
Introduction
</h1>


In [11]:
import numpy as np
mean = [10, 20]
cov = [[1, 0.5], [0.5, 1.5]]
x, y = np.random.multivariate_normal(mean, cov, 10000000).T

In [12]:
np.cov(x,y), np.corrcoef(x,y), np.mean(x), np.mean(y)

(array([[1.00072734, 0.5004859 ],
        [0.5004859 , 1.50023943]]),
 array([[1.       , 0.4084639],
        [0.4084639, 1.       ]]),
 10.000051957056066,
 19.999584023851817)

In [13]:
x_ = x-5; y_ = y-10
np.cov(x_,y_), np.corrcoef(x_,y_), np.mean(x_), np.mean(y_)

(array([[1.00072734, 0.5004859 ],
        [0.5004859 , 1.50023943]]),
 array([[1.       , 0.4084639],
        [0.4084639, 1.       ]]),
 5.000051957056082,
 9.999584023851838)

In [14]:
gamma = 0.5* np.mean((x-y)**2)
gamma

50.74531818782632

In [15]:
(cov[0][0] + cov[1][1] + (mean[0]-mean[1])**2  - 2*gamma)/2

0.5046818121736791